//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApplication.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLAUTHOR
    {
        public int AUTHORID { get; set; }
        
        public string AUTHORNAME { get; set; }
        public Nullable<byte> AUTHORAGE { get; set; }
        public Nullable<int> AUTHORGENDER { get; set; }
        public string AUTHORCOUNTRY { get; set; }
    
        public virtual TBLGENDER TBLGENDER { get; set; }
    }
}
