//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApplication.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGENDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLGENDER()
        {
            this.TBLAUTHOR = new HashSet<TBLAUTHOR>();
        }
    
        public int GENDERID { get; set; }
        public string GENDERNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLAUTHOR> TBLAUTHOR { get; set; }
    }
}
